version: '3.4'

services:
  newapp:
    image: newapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.vsdbg:/remote_debugger
